server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/red-flower?serverTimezone=GMT%2b8
    username: root
    password: qwer123789
mybatis:
  mapper-locations:
    classpath:mapper/*.xml